version: "3.9"
name: mgm-local
services:
  db:
    container_name: mgm-db-local
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: mgm
    ports:
      - 3306:3306
    volumes:
      - mgm-db-local-vol:/var/lib/mysql

volumes:
  mgm-db-local-vol:
